---
# ------------------------------------------------
# Register SNO on RHACM
# ------------------------------------------------
ocp4_workload_register_sno_cluster_name: aws-us

ocp4_workload_register_sno_rhacm_openshift_api_url: ""
ocp4_workload_register_sno_rhacm_openshift_api_token: ""

ocp4_workload_register_sno_aws_openshift_api_url: ""
ocp4_workload_register_sno_aws_openshift_api_token: ""
