---
galaxy_info:
  role_name: ocp4_workload_prepare_hcp
  author: Red Hat, Wolfgang Kulhanek (wkulhane@redhat.com)
  description: |
    Prepare to deploy a HCP cluster RHACM
  license: MIT
  min_ansible_version: "2.9"
  platforms:
  - linux
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
